version: '3.8'
services:
  flask_llm:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    command: python app/main.py
