# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /LLM_api

# Copy requirements.txt and install dependencies
COPY ./docker/requirements.txt /LLM_api/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY ./src /LLM_api

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run the app
CMD ["python", "app/main.py"]